// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"gendemo/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.Company{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Company{}) fail: %s", err)
	}
}

func Test_companyQuery(t *testing.T) {
	company := newCompany(_gen_test_db)
	company = *company.As(company.TableName())
	_do := company.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(company.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <companies> fail:", err)
		return
	}

	_, ok := company.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from company success")
	}

	err = _do.Create(&model.Company{})
	if err != nil {
		t.Error("create item in table <companies> fail:", err)
	}

	err = _do.Save(&model.Company{})
	if err != nil {
		t.Error("create item in table <companies> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Company{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <companies> fail:", err)
	}

	_, err = _do.Select(company.ALL).Take()
	if err != nil {
		t.Error("Take() on table <companies> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <companies> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <companies> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <companies> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Company{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <companies> fail:", err)
	}

	_, err = _do.Select(company.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <companies> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <companies> fail:", err)
	}

	_, err = _do.Select(company.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <companies> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <companies> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <companies> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <companies> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Company{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <companies> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <companies> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <companies> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <companies> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <companies> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <companies> fail:", err)
	}
}

var CompanyFindByNameAndAgeTestCase = []TestCase{}

func Test_company_FindByNameAndAge(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyFindByNameAndAgeTestCase {
		t.Run("FindByNameAndAge_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByNameAndAge(tt.Input.Args[0].(string), tt.Input.Args[1].(int))
			assert(t, "FindByNameAndAge", res1, tt.Expectation.Ret[0])
			assert(t, "FindByNameAndAge", res2, tt.Expectation.Ret[1])
		})
	}
}

var CompanyFindBySimpleNameTestCase = []TestCase{}

func Test_company_FindBySimpleName(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyFindBySimpleNameTestCase {
		t.Run("FindBySimpleName_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindBySimpleName()
			assert(t, "FindBySimpleName", res1, tt.Expectation.Ret[0])
			assert(t, "FindBySimpleName", res2, tt.Expectation.Ret[1])
		})
	}
}

var CompanyFindByIDOrNameTestCase = []TestCase{}

func Test_company_FindByIDOrName(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyFindByIDOrNameTestCase {
		t.Run("FindByIDOrName_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByIDOrName(tt.Input.Args[0].(bool), tt.Input.Args[1].(int), tt.Input.Args[2].(string), tt.Input.Args[3].(string))
			assert(t, "FindByIDOrName", res1, tt.Expectation.Ret[0])
			assert(t, "FindByIDOrName", res2, tt.Expectation.Ret[1])
		})
	}
}

var CompanyFindAllTestCase = []TestCase{}

func Test_company_FindAll(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyFindAllTestCase {
		t.Run("FindAll_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAll()
			assert(t, "FindAll", res1, tt.Expectation.Ret[0])
			assert(t, "FindAll", res2, tt.Expectation.Ret[1])
		})
	}
}

var CompanyFindOneTestCase = []TestCase{}

func Test_company_FindOne(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyFindOneTestCase {
		t.Run("FindOne_"+strconv.Itoa(i), func(t *testing.T) {
			res1 := do.FindOne()
			assert(t, "FindOne", res1, tt.Expectation.Ret[0])
		})
	}
}

var CompanyFindAddressTestCase = []TestCase{}

func Test_company_FindAddress(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyFindAddressTestCase {
		t.Run("FindAddress_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAddress()
			assert(t, "FindAddress", res1, tt.Expectation.Ret[0])
			assert(t, "FindAddress", res2, tt.Expectation.Ret[1])
		})
	}
}
