// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"gendemo/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.TestField{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.TestField{}) fail: %s", err)
	}
}

func Test_testFieldQuery(t *testing.T) {
	testField := newTestField(_gen_test_db)
	testField = *testField.As(testField.TableName())
	_do := testField.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(testField.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <test_fields> fail:", err)
		return
	}

	_, ok := testField.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from testField success")
	}

	err = _do.Create(&model.TestField{})
	if err != nil {
		t.Error("create item in table <test_fields> fail:", err)
	}

	err = _do.Save(&model.TestField{})
	if err != nil {
		t.Error("create item in table <test_fields> fail:", err)
	}

	err = _do.CreateInBatches([]*model.TestField{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <test_fields> fail:", err)
	}

	_, err = _do.Select(testField.ALL).Take()
	if err != nil {
		t.Error("Take() on table <test_fields> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <test_fields> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <test_fields> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <test_fields> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.TestField{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <test_fields> fail:", err)
	}

	_, err = _do.Select(testField.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <test_fields> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <test_fields> fail:", err)
	}

	_, err = _do.Select(testField.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <test_fields> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <test_fields> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <test_fields> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <test_fields> fail:", err)
	}

	_, err = _do.ScanByPage(&model.TestField{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <test_fields> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <test_fields> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <test_fields> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <test_fields> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <test_fields> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <test_fields> fail:", err)
	}
}

var TestFieldFindByNameAndAgeTestCase = []TestCase{}

func Test_testField_FindByNameAndAge(t *testing.T) {
	testField := newTestField(_gen_test_db)
	do := testField.WithContext(context.Background()).Debug()

	for i, tt := range TestFieldFindByNameAndAgeTestCase {
		t.Run("FindByNameAndAge_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByNameAndAge(tt.Input.Args[0].(string), tt.Input.Args[1].(int))
			assert(t, "FindByNameAndAge", res1, tt.Expectation.Ret[0])
			assert(t, "FindByNameAndAge", res2, tt.Expectation.Ret[1])
		})
	}
}

var TestFieldFindBySimpleNameTestCase = []TestCase{}

func Test_testField_FindBySimpleName(t *testing.T) {
	testField := newTestField(_gen_test_db)
	do := testField.WithContext(context.Background()).Debug()

	for i, tt := range TestFieldFindBySimpleNameTestCase {
		t.Run("FindBySimpleName_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindBySimpleName()
			assert(t, "FindBySimpleName", res1, tt.Expectation.Ret[0])
			assert(t, "FindBySimpleName", res2, tt.Expectation.Ret[1])
		})
	}
}

var TestFieldFindByIDOrNameTestCase = []TestCase{}

func Test_testField_FindByIDOrName(t *testing.T) {
	testField := newTestField(_gen_test_db)
	do := testField.WithContext(context.Background()).Debug()

	for i, tt := range TestFieldFindByIDOrNameTestCase {
		t.Run("FindByIDOrName_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByIDOrName(tt.Input.Args[0].(bool), tt.Input.Args[1].(int), tt.Input.Args[2].(string), tt.Input.Args[3].(string))
			assert(t, "FindByIDOrName", res1, tt.Expectation.Ret[0])
			assert(t, "FindByIDOrName", res2, tt.Expectation.Ret[1])
		})
	}
}

var TestFieldFindAllTestCase = []TestCase{}

func Test_testField_FindAll(t *testing.T) {
	testField := newTestField(_gen_test_db)
	do := testField.WithContext(context.Background()).Debug()

	for i, tt := range TestFieldFindAllTestCase {
		t.Run("FindAll_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAll()
			assert(t, "FindAll", res1, tt.Expectation.Ret[0])
			assert(t, "FindAll", res2, tt.Expectation.Ret[1])
		})
	}
}

var TestFieldFindOneTestCase = []TestCase{}

func Test_testField_FindOne(t *testing.T) {
	testField := newTestField(_gen_test_db)
	do := testField.WithContext(context.Background()).Debug()

	for i, tt := range TestFieldFindOneTestCase {
		t.Run("FindOne_"+strconv.Itoa(i), func(t *testing.T) {
			res1 := do.FindOne()
			assert(t, "FindOne", res1, tt.Expectation.Ret[0])
		})
	}
}

var TestFieldFindAddressTestCase = []TestCase{}

func Test_testField_FindAddress(t *testing.T) {
	testField := newTestField(_gen_test_db)
	do := testField.WithContext(context.Background()).Debug()

	for i, tt := range TestFieldFindAddressTestCase {
		t.Run("FindAddress_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAddress()
			assert(t, "FindAddress", res1, tt.Expectation.Ret[0])
			assert(t, "FindAddress", res2, tt.Expectation.Ret[1])
		})
	}
}
