// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"gendemo/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.User{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.User{}) fail: %s", err)
	}
}

func Test_userQuery(t *testing.T) {
	user := newUser(_gen_test_db)
	user = *user.As(user.TableName())
	_do := user.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(user.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <users> fail:", err)
		return
	}

	_, ok := user.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from user success")
	}

	err = _do.Create(&model.User{})
	if err != nil {
		t.Error("create item in table <users> fail:", err)
	}

	err = _do.Save(&model.User{})
	if err != nil {
		t.Error("create item in table <users> fail:", err)
	}

	err = _do.CreateInBatches([]*model.User{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <users> fail:", err)
	}

	_, err = _do.Select(user.ALL).Take()
	if err != nil {
		t.Error("Take() on table <users> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <users> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <users> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <users> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.User{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <users> fail:", err)
	}

	_, err = _do.Select(user.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <users> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <users> fail:", err)
	}

	_, err = _do.Select(user.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <users> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <users> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <users> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <users> fail:", err)
	}

	_, err = _do.ScanByPage(&model.User{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <users> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <users> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <users> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <users> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <users> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <users> fail:", err)
	}
}

var UserFindByNameAndAgeTestCase = []TestCase{}

func Test_user_FindByNameAndAge(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindByNameAndAgeTestCase {
		t.Run("FindByNameAndAge_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByNameAndAge(tt.Input.Args[0].(string), tt.Input.Args[1].(int))
			assert(t, "FindByNameAndAge", res1, tt.Expectation.Ret[0])
			assert(t, "FindByNameAndAge", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindBySimpleNameTestCase = []TestCase{}

func Test_user_FindBySimpleName(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindBySimpleNameTestCase {
		t.Run("FindBySimpleName_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindBySimpleName()
			assert(t, "FindBySimpleName", res1, tt.Expectation.Ret[0])
			assert(t, "FindBySimpleName", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindByIDOrNameTestCase = []TestCase{}

func Test_user_FindByIDOrName(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindByIDOrNameTestCase {
		t.Run("FindByIDOrName_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByIDOrName(tt.Input.Args[0].(bool), tt.Input.Args[1].(int), tt.Input.Args[2].(string), tt.Input.Args[3].(string))
			assert(t, "FindByIDOrName", res1, tt.Expectation.Ret[0])
			assert(t, "FindByIDOrName", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindAllTestCase = []TestCase{}

func Test_user_FindAll(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindAllTestCase {
		t.Run("FindAll_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAll()
			assert(t, "FindAll", res1, tt.Expectation.Ret[0])
			assert(t, "FindAll", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindOneTestCase = []TestCase{}

func Test_user_FindOne(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindOneTestCase {
		t.Run("FindOne_"+strconv.Itoa(i), func(t *testing.T) {
			res1 := do.FindOne()
			assert(t, "FindOne", res1, tt.Expectation.Ret[0])
		})
	}
}

var UserFindAddressTestCase = []TestCase{}

func Test_user_FindAddress(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindAddressTestCase {
		t.Run("FindAddress_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAddress()
			assert(t, "FindAddress", res1, tt.Expectation.Ret[0])
			assert(t, "FindAddress", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindByIDTestCase = []TestCase{}

func Test_user_FindByID(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindByIDTestCase {
		t.Run("FindByID_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindByID(tt.Input.Args[0].(int))
			assert(t, "FindByID", res1, tt.Expectation.Ret[0])
			assert(t, "FindByID", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindAdultTestCase = []TestCase{}

func Test_user_FindAdult(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindAdultTestCase {
		t.Run("FindAdult_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.FindAdult()
			assert(t, "FindAdult", res1, tt.Expectation.Ret[0])
			assert(t, "FindAdult", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserFindByRoleTestCase = []TestCase{}

func Test_user_FindByRole(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserFindByRoleTestCase {
		t.Run("FindByRole_"+strconv.Itoa(i), func(t *testing.T) {
			do.FindByRole(tt.Input.Args[0].(string), tt.Input.Args[1].(int))
		})
	}
}

var UserUpdateUserNameTestCase = []TestCase{}

func Test_user_UpdateUserName(t *testing.T) {
	user := newUser(_gen_test_db)
	do := user.WithContext(context.Background()).Debug()

	for i, tt := range UserUpdateUserNameTestCase {
		t.Run("UpdateUserName_"+strconv.Itoa(i), func(t *testing.T) {
			res1 := do.UpdateUserName(tt.Input.Args[0].(string), tt.Input.Args[1].(int))
			assert(t, "UpdateUserName", res1, tt.Expectation.Ret[0])
		})
	}
}
